#!/usr/bin/python3

import os

# Get the Python code from the PYCODE environment variable
pycode = os.environ.get("PYCODE")

if pycode:
	exec(pycode)
else:
	print("Error: PYCODE environment variable is not set.")
